"""add function_call_logs idempotency cache

Revision ID: 9174309fbc81
Revises: db971cc049bb
Create Date: 2026-06-21 06:47:54.788597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9174309fbc81'
down_revision: Union[str, Sequence[str], None] = 'db971cc049bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('function_call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.String(length=255), nullable=False),
    sa.Column('function_name', sa.String(length=64), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'function_name', name='uq_call_id_function_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('function_call_logs')
    # ### end Alembic commands ###
