"""add post_call_processed flag to call_logs

Revision ID: e7b196f21716
Revises: 9174309fbc81
Create Date: 2026-06-21 15:39:47.853980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b196f21716'
down_revision: Union[str, Sequence[str], None] = '9174309fbc81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_logs', sa.Column('post_call_processed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_logs', 'post_call_processed')
    # ### end Alembic commands ###
